Repository guanshiyin28/MPW-Rent-Car, pull requests merged in 2025-01, with the labels that each got.

#2 Description
  index.php
Labels: documentation

#3 Doc/car single
  about.php
  car-single.php
  services.php
Labels: documentation

#4 Deploy
  about.php
  car-single.php
  services.php
  sql/webrentalmobil.sql
Labels: documentation

#5 Doc
  blog-single.php
Labels: bug, documentation

#7 Deploy
  contact.php
Labels: documentation

#8 Update Index
  index.php
Labels: documentation

#9 Deploy
  blog-single.php
  index.php
Labels: documentation

#11 Deploy
  keterangan detail sistem pembokingan.php
Labels: documentation

#12 Staging
  keterangan detail sistem pembokingan.php
Labels: documentation

#20 Create README.md
  README.md
Labels: documentation

#22 Sync Project
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE
  PULL_REQUEST_TEMPLATE.md
  SECURITY.md
Labels: documentation, enhancement
